/:
  controller: Main
  action: default

/lbly-admin:
  controller: Main
  action: dashboard

/lbly-admin/s-inscrire:
  controller: Security
  action: register

/lbly-admin/register:
  controller: Security
  action: register

/lbly-admin/se-connecter:
  controller: Security
  action: login

/lbly-admin/login:
  controller: Security
  action: login

/lbly-admin/logout:
  controller: Security
  action: logout

/lbly-admin/se-deconnecter:
  controller: Security
  action: logout

/lbly-admin/editprofil:
  controller: Security
  action: editProfil

/lbly-admin/superadminview:
  controller: SuperAdmin
  action: default

/lbly-admin/uservalidated:
  controller: Security
  action: uservalidated

/lbly-admin/userconfirm:
  controller: Security
  action: userconfirm

/lbly-admin/pages:
  controller: PageController
  action: default

/lbly-admin/pages/add:
  controller: PageController
  action: addpage

/lbly-admin/category:
  controller: CategoryController
  action: addcategory

/lbly-admin/books:
  controller: BookController
  action: index

/lbly-admin/articles:
  controller: ArticleController
  action: default

/lbly-admin/articles/add:
  controller: ArticleController
  action: addArticle

/lbly-admin/articles/edit:
  controller: ArticleController
  action: editArticle
