/:
  controller: Main
  action: default

/lbly-admin:
  controller: Main
  action: dashboard

/lbly-admin/settings:
  controller: Settings
  action: changeSettings

/lbly-admin/s-inscrire:
  controller: Security
  action: register

/lbly-admin/register:
  controller: Security
  action: register

/lbly-admin/se-connecter:
  controller: Security
  action: login

/lbly-admin/login:
  controller: Security
  action: login

/lbly-admin/logout:
  controller: Security
  action: logout

/lbly-admin/se-deconnecter:
  controller: Security
  action: logout

/lbly-admin/editprofil:
  controller: Security
  action: editProfil

/lbly-admin/adminview:
  controller: Security
  action: getAllUsers

/lbly-admin/changerole:
  controller: Security
  action: modifyRole

/deleteuser:
  controller: Security
  action: deleteUser

/lbly-admin/uservalidated:
  controller: Security
  action: uservalidated

/lbly-admin/userconfirm:
  controller: Security
  action: userconfirm

/lbly-admin/pages:
  controller: Page
  action: default

/lbly-admin/pages/add:
  controller: Page
  action: addpage

/lbly-admin/category:
  controller: Category
  action: default

/lbly-admin/category/add:
  controller: Category
  action: addCategory

/lbly-admin/books:
  controller: Book
  action: default

/lbly-admin/books/add:
  controller: Book
  action: addBook

/lbly-admin/articles:
  controller: Article
  action: default

/lbly-admin/articles/add:
  controller: Article
  action: addArticle

/lbly-admin/articles/edit:
  controller: Article
  action: editArticle

/lbly-admin/books/edit:
  controller: Book
  action: editBook

/lbly-admin/orders:
  controller: Order
  action: default

/forgetpwd:
  controller: Security
  action: forgetPwd

/resetpwd:
  controller: Security
  action: resetPwd

/installer:
  controller: Installer
  action: default

/cart:
  controller: Cart
  action: default

/cart/confirm:
  controller: Order
  action: confirmCart
  
/payment-success:
  controller: Order
  action: success

/books:
  controller: Book
  action: seeAllBooks
