/:
  controller: Main
  action: default

/admin:
  controller: Security
  action: default

/s-inscrire:
  controller: Security
  action: register

/register:
  controller: Security
  action: register

/se-connecter:
  controller: Security
  action: login

/login:
  controller: Security
  action: login

/logout:
  controller: Security
  action: logout

/se-deconnecter:
  controller: Security
  action: logout

/editprofil:
  controller: Security
  action: editProfil

/superadminview:
  controller: SuperAdmin
  action: default

/uservalidated:
  controller: Security
  action: uservalidated

/userconfirm:
  controller: Security
  action: userconfirm

/page/all:
  controller: PageController
  action: default

/page/add:
  controller: PageController
  action: addpage

/category:
  controller: CategoryController
  action: addcategory

/books:
  controller: BookController
  action: index

/articles:
  controller: ArticleController
  action: default

/articles/add:
  controller: ArticleController
  action: addArticle

/articles/edit:
  controller: ArticleController
  action: editArticle
