
/:
  controller: Main
  action: default

/admin:
  controller: Security
  action: default

/s-inscrire:
  controller: Security
  action: register

/register:
  controller: Security
  action: register

/se-connecter:
  controller: Security
  action: login

/login:
  controller: Security
  action: login  

/logout:
  controller: Security
  action: logout

/se-deconnecter:
  controller: Security
  action: logout

/editprofil:
  controller: Security
  action: editProfil

/category:
  controller: CategoryController
  action: addcategory
