/:
  controller: Main
  action: default

/lbly-admin:
  controller: Main
  action: dashboard

/lbly-admin/s-inscrire:
  controller: Security
  action: register

/lbly-admin/register:
  controller: Security
  action: register

/lbly-admin/se-connecter:
  controller: Security
  action: login

/lbly-admin/login:
  controller: Security
  action: login

/lbly-admin/logout:
  controller: Security
  action: logout

/lbly-admin/se-deconnecter:
  controller: Security
  action: logout

/lbly-admin/editprofil:
  controller: Security
  action: editProfil

/lbly-admin/superadminview:
  controller: SuperAdmin
  action: default

/lbly-admin/uservalidated:
  controller: Security
  action: uservalidated

/lbly-admin/userconfirm:
  controller: Security
  action: userconfirm

/lbly-admin/pages:
  controller: Page
  action: default

/lbly-admin/pages/add:
  controller: Page
  action: addpage

/lbly-admin/category:
  controller: Category
  action: index

/lbly-admin/books:
  controller: Book
  action: index

/lbly-admin/articles:
  controller: Article
  action: default

/lbly-admin/articles/add:
  controller: Article
  action: addArticle

/lbly-admin/articles/edit:
  controller: Article
  action: editArticle

/forgetpwd:
  controller: Security
  action: forgetPwd

/resetpwd:
  controller: Security
  action: resetPwd
